### ISSUE TITLE
49版本闪退

### ISSUE THREAD

**Issue by zzh1004211573** [MAT-OUT/tellyouhowdoit#1]
下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退

**Comment by zzh1004211573** [comment]
> 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退

**Comment by MAT-OUT** [comment]
> 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退

50呢。

**Comment by zzh1004211573** [comment]
> > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> 
> 50呢。

没有试 

> > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> 
> 50呢。

50没事！ 49我三个版本都试了 全都闪退😩

**Comment by MAT-OUT** [comment]
> > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > 
> > 
> > 50呢。
> 
> 没有试
> 
> > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > 
> > 
> > 50呢。
> 
> 50没事！ 49我三个版本都试了 全都闪退😩

哦不，49改崩了，目前只能不看动态凑合，日后再弄个新的

**Comment by zzh1004211573** [comment]
> > > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > > 
> > > 
> > > 50呢。
> > 
> > 
> > 没有试
> > > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > > 
> > > 
> > > 50呢。
> > 
> > 
> > 50没事！ 49我三个版本都试了 全都闪退😩
> 
> 哦不，49改崩了，目前只能不看动态凑合，日后再弄个新的

辛苦大佬😆

**Comment by MAT-OUT** [comment]
> > > > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > > > 
> > > > 
> > > > 50呢。
> > > 
> > > 
> > > 没有试
> > > > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > > > 
> > > > 
> > > > 50呢。
> > > 
> > > 
> > > 50没事！ 49我三个版本都试了 全都闪退😩
> > 
> > 
> > 哦不，49改崩了，目前只能不看动态凑合，日后再弄个新的
> 
> 辛苦大佬😆

试下 50 稳定版，目前不想编译新版漫游了，凑合用

**Comment by zzh1004211573** [comment]
> > > > > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > > > > 
> > > > > 
> > > > > 50呢。
> > > > 
> > > > 
> > > > 没有试
> > > > > > 下载了带插件和新不带插件的版本 下滑动态到指定位置就闪退
> > > > > 
> > > > > 
> > > > > 50呢。
> > > > 
> > > > 
> > > > 50没事！ 49我三个版本都试了 全都闪退😩
> > > 
> > > 
> > > 哦不，49改崩了，目前只能不看动态凑合，日后再弄个新的
> > 
> > 
> > 辛苦大佬😆
> 
> 试下 50 稳定版，目前不想编译新版漫游了，凑合用

50版本很好 啥问题都没得👏👏
