### ISSUE TITLE
release里缺少No Xposed的哔哩哔哩 6.58.0 Super 稳定版

### ISSUE THREAD

**Issue by ClannadWorld** [MAT-OUT/tellyouhowdoit#10]
release里缺少No Xposed的哔哩哔哩 6.58.0 Super 稳定版

**Comment by MAT-OUT** [comment]
INDEED, BUT I HAVE NO TIME NOW

**Comment by MAT-OUT** [comment]
> release里缺少No Xposed的哔哩哔哩 6.58.0 Super 稳定版

你可以自行把启动入口改回mt去校验那个类，就没有内置了

**Comment by MAT-OUT** [comment]
> release里缺少No Xposed的哔哩哔哩 6.58.0 Super 稳定版

当然现在也提供了
