### ISSUE TITLE
Lspatch.Without.Modules使用哔哩漫游添加频道底栏，频道部分显示不全

### ISSUE THREAD

**Issue by Mingtu2019** [MAT-OUT/tellyouhowdoit#3]
系统: 安卓9 
版本: Bilibili.6.50.0.Final.Lspatch.Without.Modules.apk
问题: 使用哔哩漫游添加频道底栏，频道部分显示不全，下滑到最下面卡住，无法继续下滑，屏幕三键导航更换为屏幕手势导航问题也会出现
谢谢！
如图: 
![Screenshot_20211128_104727](https://user-images.githubusercontent.com/49590221/143726991-a4167930-b2f3-47ed-b73e-e98294c8dcd1.jpg)

**Comment by MAT-OUT** [comment]
> 系统: 安卓9 版本: Bilibili.6.50.0.Final.Lspatch.Without.Modules.apk 问题: 使用哔哩漫游添加频道底栏，频道部分显示不全，下滑到最下面卡住，无法继续下滑，屏幕三键导航更换为屏幕手势导航问题也会出现 谢谢！ 如图: ![Screenshot_20211128_104727](https://user-images.githubusercontent.com/49590221/143726991-a4167930-b2f3-47ed-b73e-e98294c8dcd1.jpg)

分辨率和底栏布局的锅，不过有招，稍等

**Comment by MAT-OUT** [comment]
> 系统: 安卓9 版本: Bilibili.6.50.0.Final.Lspatch.Without.Modules.apk 问题: 使用哔哩漫游添加频道底栏，频道部分显示不全，下滑到最下面卡住，无法继续下滑，屏幕三键导航更换为屏幕手势导航问题也会出现 谢谢！ 如图: ![Screenshot_20211128_104727](https://user-images.githubusercontent.com/49590221/143726991-a4167930-b2f3-47ed-b73e-e98294c8dcd1.jpg)

https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file
试试

**Comment by Mingtu2019** [comment]
> > 系统: 安卓9 版本: Bilibili.6.50.0.Final.Lspatch.Without.Modules.apk 问题: 使用哔哩漫游添加频道底栏，频道部分显示不全，下滑到最下面卡住，无法继续下滑，屏幕三键导航更换为屏幕手势导航问题也会出现 谢谢！ 如图: ![Screenshot_20211128_104727](https://user-images.githubusercontent.com/49590221/143726991-a4167930-b2f3-47ed-b73e-e98294c8dcd1.jpg)
> 
> https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 试试

谢谢大佬
比上次多了一点，不过还是没显示完
分辨率是 2340*1080，6.5英寸
![Screenshot_20211129_151739](https://user-images.githubusercontent.com/49590221/143824444-d603af03-4e6e-471b-abce-71cd4d8327af.jpg)

**Comment by MAT-OUT** [comment]
> 系统: 安卓9 版本: Bilibili.6.50.0.Final.Lspatch.Without.Modules.apk 问题: 使用哔哩漫游添加频道底栏，频道部分显示不全，下滑到最下面卡住，无法继续下滑，屏幕三键导航更换为屏幕手势导航问题也会出现 谢谢！ 如图: ![Screenshot_20211128_104727](https://user-images.githubusercontent.com/49590221/143726991-a4167930-b2f3-47ed-b73e-e98294c8dcd1.jpg)

感觉是你dpi的问题。。。太大了把

**Comment by Mingtu2019** [comment]
> > 系统: 安卓9 版本: Bilibili.6.50.0.Final.Lspatch.Without.Modules.apk 问题: 使用哔哩漫游添加频道底栏，频道部分显示不全，下滑到最下面卡住，无法继续下滑，屏幕三键导航更换为屏幕手势导航问题也会出现 谢谢！ 如图: ![Screenshot_20211128_104727](https://user-images.githubusercontent.com/49590221/143726991-a4167930-b2f3-47ed-b73e-e98294c8dcd1.jpg)
> 
> 感觉是你dpi的问题。。。太大了把
高度是有点高，😂
