### ISSUE TITLE
color12打开闪退，用内置版本直接打不开，用不内置的版本能打开识别不了漫游

### ISSUE THREAD

**Issue by dasiuhj** [MAT-OUT/tellyouhowdoit#4]

**Comment by MAT-OUT** [comment]
我知道，安卓12的锅可能是漫游还没适配好

**Comment by dasiuhj** [comment]
> 我知道，安卓12的锅可能是漫游还没适配好

tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受

**Comment by MAT-OUT** [comment]
> > 我知道，安卓12的锅可能是漫游还没适配好
> 
> tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受

哪个？，体积 80+的那种？

**Comment by MAT-OUT** [comment]
> > 我知道，安卓12的锅可能是漫游还没适配好
> 
> tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受

https://wwe.lanzoux.com/b015ll4sb
这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了

**Comment by dasiuhj** [comment]
> 

对就是80多m的，

**Comment by dasiuhj** [comment]
> > > 我知道，安卓12的锅可能是漫游还没适配好
> > 
> > 
> > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> 
> https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了

这密码是多少进不去

**Comment by dasiuhj** [comment]
> > > 我知道，安卓12的锅可能是漫游还没适配好
> > 
> > 
> > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> 
> https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了

这个没问题，不闪退正常使用

**Comment by MAT-OUT** [comment]
> > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > 
> > > 
> > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > 
> > 
> > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> 
> 这个没问题，不闪退正常使用

https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file
这个呢，我加了log输出，你看看日志给我，我去反馈下

**Comment by dasiuhj** [comment]
- [ ]

**Comment by dasiuhj** [comment]
> > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > 
> > > > 
> > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > 
> > > 
> > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > 
> > 
> > 这个没问题，不闪退正常使用
> 
> https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下

[log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt)
打不开也不会闪退

**Comment by MAT-OUT** [comment]
> > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > 
> > > > > 
> > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > 
> > > > 
> > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > 
> > > 
> > > 这个没问题，不闪退正常使用
> > 
> > 
> > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> 
> [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退

有ROOT吗

> > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > 
> > > > > 
> > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > 
> > > > 
> > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > 
> > > 
> > > 这个没问题，不闪退正常使用
> > 
> > 
> > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> 
> [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退

有ROOT吗

**Comment by dasiuhj** [comment]
> > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > 
> > > > > > 
> > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > 
> > > > > 
> > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > 
> > > > 
> > > > 这个没问题，不闪退正常使用
> > > 
> > > 
> > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > 
> > 
> > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> 
> 有ROOT吗
> 
> > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > 
> > > > > > 
> > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > 
> > > > > 
> > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > 
> > > > 
> > > > 这个没问题，不闪退正常使用
> > > 
> > > 
> > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > 
> > 
> > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> 
> 有ROOT吗

没有x3p没有深度测试

**Comment by dasiuhj** [comment]
> > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > 
> > > > > > > > 
> > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > 
> > > > > > > 
> > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > 
> > > > > > 
> > > > > > 这个没问题，不闪退正常使用
> > > > > 
> > > > > 
> > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > 
> > > > 
> > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > 
> > > 
> > > 有ROOT吗
> > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > 
> > > > > > > > 
> > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > 
> > > > > > > 
> > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > 
> > > > > > 
> > > > > > 这个没问题，不闪退正常使用
> > > > > 
> > > > > 
> > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > 
> > > > 
> > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > 
> > > 
> > > 有ROOT吗
> > 
> > 
> > 没有x3p没有深度测试
> 
> 大概知道了，估计要换框架喽

需要我帮你测试吗？

**Comment by MAT-OUT** [comment]
> > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > 
> > > > > > > 
> > > > > > > 这个没问题，不闪退正常使用
> > > > > > 
> > > > > > 
> > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > 
> > > > > 
> > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > 
> > > > 
> > > > 有ROOT吗
> > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > 
> > > > > > > 
> > > > > > > 这个没问题，不闪退正常使用
> > > > > > 
> > > > > > 
> > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > 
> > > > > 
> > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > 
> > > > 
> > > > 有ROOT吗
> > > 
> > > 
> > > 没有x3p没有深度测试
> > 
> > 
> > 大概知道了，估计要换框架喽
> 
> 需要我帮你测试吗？

不用了，我回退框架了，你自己试试

**Comment by dasiuhj** [comment]
> > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > 
> > > > > > > 
> > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > 
> > > > > > 
> > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > 
> > > > > 
> > > > > 有ROOT吗
> > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > 
> > > > > > > 
> > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > 
> > > > > > 
> > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > 
> > > > > 
> > > > > 有ROOT吗
> > > > 
> > > > 
> > > > 没有x3p没有深度测试
> > > 
> > > 
> > > 大概知道了，估计要换框架喽
> > 
> > 
> > 需要我帮你测试吗？
> 
> 不用了，我回退框架了，你自己试试

好

**Comment by dasiuhj** [comment]
> > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > 
> > > > > > > 
> > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > 
> > > > > > 
> > > > > > 有ROOT吗
> > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > 
> > > > > > > 
> > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > 
> > > > > > 
> > > > > > 有ROOT吗
> > > > > 
> > > > > 
> > > > > 没有x3p没有深度测试
> > > > 
> > > > 
> > > > 大概知道了，估计要换框架喽
> > > 
> > > 
> > > 需要我帮你测试吗？
> > 
> > 
> > 不用了，我回退框架了，你自己试试
> 
> 好

可以用，没问题，谢谢大佬

**Comment by dasiuhj** [comment]
> > > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > > 
> > > > > > > 
> > > > > > > 有ROOT吗
> > > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > > 
> > > > > > > 
> > > > > > > 有ROOT吗
> > > > > > 
> > > > > > 
> > > > > > 没有x3p没有深度测试
> > > > > 
> > > > > 
> > > > > 大概知道了，估计要换框架喽
> > > > 
> > > > 
> > > > 需要我帮你测试吗？
> > > 
> > > 
> > > 不用了，我回退框架了，你自己试试
> > 
> > 
> > 好
> 
> 可以用，没问题，谢谢大佬

大哥，你用的是什么版本的lspatch，我想自己打包个抖音

**Comment by MAT-OUT** [comment]
> > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > 
> > > > > > > 
> > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > 
> > > > > > 
> > > > > > 有ROOT吗
> > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > 
> > > > > > > 
> > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > 
> > > > > > 
> > > > > > 有ROOT吗
> > > > > 
> > > > > 
> > > > > 没有x3p没有深度测试
> > > > 
> > > > 
> > > > 大概知道了，估计要换框架喽
> > > 
> > > 
> > > 需要我帮你测试吗？
> > 
> > 
> > 不用了，我回退框架了，你自己试试
> 
> 好

上传了一个

**Comment by dasiuhj** [comment]
> > > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > > 
> > > > > > > 
> > > > > > > 有ROOT吗
> > > > > > > > > > > > > 我知道，安卓12的锅可能是漫游还没适配好
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > tg上有个用Lspatch修改的可以完美识别漫游也不闪退，就是广告没有去全，动态很多广告有点难受
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > https://wwe.lanzoux.com/b015ll4sb 这里的安卓12闪退不？如果不闪退，那就要把问题聚焦于新版 lspatch 了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 这个没问题，不闪退正常使用
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > https://www.mediafire.com/file/zf62nr669mf93mh/Bilibili_6.50.0_Log_Lspatch_With_Modules.apk/file 这个呢，我加了log输出，你看看日志给我，我去反馈下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [log.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7616863/log.txt) 打不开也不会闪退
> > > > > > > 
> > > > > > > 
> > > > > > > 有ROOT吗
> > > > > > 
> > > > > > 
> > > > > > 没有x3p没有深度测试
> > > > > 
> > > > > 
> > > > > 大概知道了，估计要换框架喽
> > > > 
> > > > 
> > > > 需要我帮你测试吗？
> > > 
> > > 
> > > 不用了，我回退框架了，你自己试试
> > 
> > 
> > 好
> 
> 上传了一个

好的谢谢，大哥
