### ISSUE TITLE
50稳定版动态闪退

### ISSUE THREAD

**Issue by recycle007** [MAT-OUT/tellyouhowdoit#5]
往下滑一会就闪退了，不带框架模块版本

**Comment by MAT-OUT** [comment]
> 往下滑一会就闪退了，不带框架模块版本

现在不可能啊，你用FIXED啊，重新上传了

**Comment by recycle007** [comment]
> > 往下滑一会就闪退了，不带框架模块版本
> 
> 现在不可能啊，你用FIXED啊，重新上传了

就是昨天刚装的呀

**Comment by MAT-OUT** [comment]
> > > 往下滑一会就闪退了，不带框架模块版本
> > 
> > 
> > 现在不可能啊，你用FIXED啊，重新上传了
> 
> 就是昨天刚装的呀

没有LOG就算了，凭空修BUG换上帝也做不到啊

**Comment by recycle007** [comment]
> > > > 往下滑一会就闪退了，不带框架模块版本
> > > 
> > > 
> > > 现在不可能啊，你用FIXED啊，重新上传了
> > 
> > 
> > 就是昨天刚装的呀
> 
> 没有LOG就算了，凭空修BUG换上帝也做不到啊

log在哪里呀，我看看

**Comment by MAT-OUT** [comment]
> > > > > 往下滑一会就闪退了，不带框架模块版本
> > > > 
> > > > 
> > > > 现在不可能啊，你用FIXED啊，重新上传了
> > > 
> > > 
> > > 就是昨天刚装的呀
> > 
> > 
> > 没有LOG就算了，凭空修BUG换上帝也做不到啊
> 
> log在哪里呀，我看看

唉，算了，要ROOT的，我已经知道什么问题了。

**Comment by recycle007** [comment]
> > > > > > 往下滑一会就闪退了，不带框架模块版本
> > > > > 
> > > > > 
> > > > > 现在不可能啊，你用FIXED啊，重新上传了
> > > > 
> > > > 
> > > > 就是昨天刚装的呀
> > > 
> > > 
> > > 没有LOG就算了，凭空修BUG换上帝也做不到啊
> > 
> > 
> > log在哪里呀，我看看
> 
> 唉，算了，要ROOT的，我已经知道什么问题了。

我root了，是lsposed的模块日志吗

**Comment by MAT-OUT** [comment]
> > > > > > > 往下滑一会就闪退了，不带框架模块版本
> > > > > > 
> > > > > > 
> > > > > > 现在不可能啊，你用FIXED啊，重新上传了
> > > > > 
> > > > > 
> > > > > 就是昨天刚装的呀
> > > > 
> > > > 
> > > > 没有LOG就算了，凭空修BUG换上帝也做不到啊
> > > 
> > > 
> > > log在哪里呀，我看看
> > 
> > 
> > 唉，算了，要ROOT的，我已经知道什么问题了。
> 
> 我root了，是lsposed的模块日志吗

是崩溃日志记录，一般看不了，不过我知道什么问题了，bugly 移除还残留了代码，删掉就好了，因为我也闪退了，不然嘿嘿，我都懒得修了

**Comment by recycle007** [comment]
> > > > > > > > 往下滑一会就闪退了，不带框架模块版本
> > > > > > > 
> > > > > > > 
> > > > > > > 现在不可能啊，你用FIXED啊，重新上传了
> > > > > > 
> > > > > > 
> > > > > > 就是昨天刚装的呀
> > > > > 
> > > > > 
> > > > > 没有LOG就算了，凭空修BUG换上帝也做不到啊
> > > > 
> > > > 
> > > > log在哪里呀，我看看
> > > 
> > > 
> > > 唉，算了，要ROOT的，我已经知道什么问题了。
> > 
> > 
> > 我root了，是lsposed的模块日志吗
> 
> 是崩溃日志记录，一般看不了，不过我知道什么问题了，bugly 移除还残留了代码，删掉就好了，因为我也闪退了，不然嘿嘿，我都懒得修了

等个更新🤓
