### ISSUE TITLE
库精简

### ISSUE THREAD

**Issue by WhiCCX0** [MAT-OUT/tellyouhowdoit#6]
可以删除一些没用的库文件。
![Screenshot_20211203-205329_Lawnchair](https://user-images.githubusercontent.com/47388635/144605875-b85ed3c1-3022-411d-bdfb-e20ef6e94e1f.png)
![Screenshot_20211203-205334_Lawnchair](https://user-images.githubusercontent.com/47388635/144605885-6fef34cc-a089-4268-8cb6-c01ee102c77c.png)
如bugly，银联和微博sdk。
删除后仍能正常使用。
删除后的库：
![Screenshot_20211203-205533_Lawnchair](https://user-images.githubusercontent.com/47388635/144606064-b79c3383-241d-466f-9cb9-c38440c07284.png)

**Comment by MAT-OUT** [comment]
> 可以删除一些没用的库文件。 ![Screenshot_20211203-205329_Lawnchair](https://user-images.githubusercontent.com/47388635/144605875-b85ed3c1-3022-411d-bdfb-e20ef6e94e1f.png) ![Screenshot_20211203-205334_Lawnchair](https://user-images.githubusercontent.com/47388635/144605885-6fef34cc-a089-4268-8cb6-c01ee102c77c.png) 如bugly，银联和微博sdk。 删除后仍能正常使用。 删除后的库： ![Screenshot_20211203-205533_Lawnchair](https://user-images.githubusercontent.com/47388635/144606064-b79c3383-241d-466f-9cb9-c38440c07284.png)

银联那个是不是影响支付

**Comment by WhiCCX0** [comment]
去除之后确实影响了银联的支付，其他如支付宝微信等都能正常使用，可以不去除这个

**Comment by MAT-OUT** [comment]
> 去除之后确实影响了银联的支付，其他如支付宝微信等都能正常使用，可以不去除这个

目前自己动手，我暂时不愿意去改它
