### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by zzh1004211573** [MAT-OUT/tellyouhowdoit#8]
今晚最新版点击动态就闪退 换了个官方就没事 是我的原因么 64位新框架带漫游版本

**Comment by clbclby** [comment]
同样有这个问题，动态页面闪退，其它部分完美，没有任何问题。

**Comment by EvatsugDnalloR** [comment]
6.50.0稳定版也有这个问题，换了6.56.0的speed就能用了... 望修复

**Comment by MAT-OUT** [comment]
> 今晚最新版点击动态就闪退 换了个官方就没事 是我的原因么 64位新框架带漫游版本

好，我需要排查一下。

**Comment by MAT-OUT** [comment]
> 同样有这个问题，动态页面闪退，其它部分完美，没有任何问题。

点开的UP主推荐一个，有的貌似并不闪退，给我一个明确闪退的

**Comment by EvatsugDnalloR** [comment]
> > 同样有这个问题，动态页面闪退，其它部分完美，没有任何问题。
> 
> 点开的UP主推荐一个，有的貌似并不闪退，给我一个明确闪退的

使用6.50.0的稳定版登陆以后点开动态百分百闪退，经过排查应该跟哔哩漫游没关系。版本是安卓11，这个现象是从昨天下午突然1开始的，早上还好好的...
但使用6.56.0的speed版就不会有这个情况，这两个包的大区别可能只剩Bugly了，但这点不确定...

**Comment by MAT-OUT** [comment]
TRY，看看还会不会闪退

**Comment by EvatsugDnalloR** [comment]
> TRY，看看还会不会闪退

试了一下，还是会闪退。登陆以后点击动态加载的时候就会闪退
顺便说一下我之前用的不是带mod的，用的是不带xposed框架的（自己加），也有同样的问题。

**Comment by MAT-OUT** [comment]
> > TRY，看看还会不会闪退
> 
> 试了一下，还是会闪退。登陆以后点击动态加载的时候就会闪退 顺便说一下我之前用的不是带mod的，用的是不带xposed框架的（自己加），也有同样的问题。

问下是哪个动态，是底栏的？还是up主的

**Comment by EvatsugDnalloR** [comment]
> > > TRY，看看还会不会闪退
> > 
> > 试了一下，还是会闪退。登陆以后点击动态加载的时候就会闪退 顺便说一下我之前用的不是带mod的，用的是不带xposed框架的（自己加），也有同样的问题。
> 
> 问下是哪个动态，是底栏的？还是up主的

底栏

**Comment by MAT-OUT** [comment]
> > > > TRY，看看还会不会闪退
> > > 
> > > 
> > > 试了一下，还是会闪退。登陆以后点击动态加载的时候就会闪退 顺便说一下我之前用的不是带mod的，用的是不带xposed框架的（自己加），也有同样的问题。
> > 
> > 
> > 问下是哪个动态，是底栏的？还是up主的
> 
> 底栏

除非你有崩溃LOG，不然应该只能等我触发再修

**Comment by EvatsugDnalloR** [comment]
> 

抓好了，不知道能不能帮上忙
[logcat.txt](https://github.com/MAT-OUT/tellyouhowdoit/files/7963690/logcat.txt)
顺便说一下经过测试并不是刚登陆一点动态就闪退，这次测试一开始进动态没任何问题，还以为不用logcat了，结果过了一会儿又开始闪退了...

**Comment by MAT-OUT** [comment]
排到了，充值后大会员引发的BUG

**Comment by MAT-OUT** [comment]
由于没有VIP，无法继续排查，此项目需要停更
