### ISSUE TITLE
希望可以不要禁用主题

### ISSUE THREAD

**Issue by EvatsugDnalloR** [MAT-OUT/tellyouhowdoit#9]
一个小建议

**Comment by MAT-OUT** [comment]
个性装扮很多人用么

**Comment by EvatsugDnalloR** [comment]
> 个性装扮很多人用么

我估计还是不少的，b站评论区逛一圈有主题的占大多数...
其实不管是6.50.0稳定版还是6.56.0的speed版都是能通过我的界面的左上角主题按钮然后进入个性装扮的，所以不需要给它单独保留一个按钮，只是希望不要禁用。比如6.56.0speed版刚装备完的时候可以用，但退出重进后就没了。只是希望把这个取消

**Comment by MAT-OUT** [comment]
> > 个性装扮很多人用么
> 
> 我估计还是不少的，b站评论区逛一圈有主题的占大多数... 其实不管是6.50.0稳定版还是6.56.0的speed版都是能通过我的界面的左上角主题按钮然后进入个性装扮的，所以不需要给它单独保留一个按钮，只是希望不要禁用。比如6.56.0speed版刚装备完的时候可以用，但退出重进后就没了。只是希望把这个取消

目前肯定是不会去更新带有个性装扮的，只能等日后再整，自从用了WSA后，修改程度麻烦几何上升，没办法直接读取WSA系统目录

**Comment by MAT-OUT** [comment]
满足一次，在6.58.0，日后不再提供，想要使用，请使用官方，我非常讨厌这个个性装扮，什么杀马特主题
